service: "album-cover-generator"

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'prod'}
  region: eu-west-2
  deploymentBucket:
    # blockPublicAccess: true
    name: serverless-${self:service}
  stackTags:
    Project: ${self:service}
    deployed_by: "Theo"
    deployed_tag: ${opt:stage, 'prod'}
  environment:
    ENV: ${self:provider.stage}
    LOG_LEVEL: ${self:custom.logLevel.${self:custom.myStage}, 'INFO'}
    # Powertools config
    POWERTOOLS_SERVICE_NAME: ${self:service}
    POWERTOOLS_METRICS_NAMESPACE: "Recordle"
    # AWS
    S3_ACCESS_KEY: ${ssm:/recordle/s3_access_key}
    S3_SECRET_KEY: ${ssm:/recordle/s3_secret_key}
    # Spotify
    SPOTIPY_CLIENT_ID: ${ssm:/recordle/spotify_client_id}
    SPOTIPY_CLIENT_SECRET: ${ssm:/recordle/spotify_client_secret}
    SPOTIPY_REDIRECT_URI: ${ssm:/recordle/spotify_redirect_uri}
    # Replicate
    REPLICATE_API_TOKEN: ${ssm:/recordle/replicate_api_token}
    # Instagram
    IG_ACCOUNT_ID: ${ssm:/recordle/ig_account_id}
    IG_REDIRECT_URL: ${ssm:/recordle/ig_redirect_url}
    IG_ACCESS_TOKEN: ${ssm:/recordle/ig_access_token}
    IG_LL_ACCESS_TOKEN: ${ssm:/recordle/ig_ll_access_token}
    IG_CLIENT_ID: ${ssm:/recordle/ig_client_id}
    IG_CLIENT_SECRET: ${ssm:/recordle/ig_client_secret}
  memorySize: 128
  timeout: 5
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:List*"
        - "s3:Get*"
      Resource: arn:aws:s3:::alt-covers-bucket/*
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "*"

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-deployment-bucket

custom:
  myStage: ${self:provider.stage}
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    useDownloadCache: true
    useStaticCache: true
    invalidateCaches: false
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pkgresources
      - python-dateutil
      - setuptools
      - s3transfer
      - six
      - pip
    # slim to reduce package size, but customise patterns to avoid breaking jsonschema
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
      - "**/*.pyc"
      - "**/*.pyo"
      - "**/__pycache__*"

# you can add packaging information here
package:
  exclude:
    - bin/**
    - coverage/**
    - logs/**
    - node_modules/**
    - htmlcov/**
    - tests/**
    - venv/**
    - .coverage
    - .test-reports/**
    - .vscode/**
    - package-lock.json
    - .ipynb_checkpoints/**
    - img/**
    - data/**
    - notebooks/**

functions:
  coverGenerator:
    description: Generates stable diff covers everyday at midnight
    handler: src.handlers.main.handler
    timeout: 300
    events:
      - schedule:
          rate: cron(0 0 ? * * *)
          enabled: true
          input:
            period: day
